### ISSUE TITLE
Implement raw string escape logic

### ISSUE THREAD

**Issue by Glyphack** [Glyphack/enderpy#102]
The raw strings currently have a separate token which is not a good idea.
We should use the same Fstring and String tokens for raw strings but when reading in the values for those strings escape the characters:

https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals

**Comment by Glyphack** [comment]
https://github.com/Glyphack/enderpy/blob/419b1ec42e83a6cb007c374ca9874808a4c9846d/parser/src/token.rs#L93

Example

>>> print(ast.dump(ast.parse(r"s = 'Hi\nHello'")))
Module(body=[Assign(targets=[Name(id='s', ctx=Store())], value=Constant(value='Hi\nHello'))], type_ignores=[])
>>> print(ast.dump(ast.parse(r"s = r'Hi\nHello'")))
Module(body=[Assign(targets=[Name(id='s', ctx=Store())], value=Constant(value='Hi\\nHello'))], type_ignores=[])

**Comment by ghodsizadeh** [comment]
Tried to fix that on this PR:
https://github.com/Glyphack/enderpy/pull/184
