### ISSUE TITLE
Add Hover Capabilities to LSP

### ISSUE THREAD

**Issue by limiteinductive** [Glyphack/enderpy#225]
To enhance the LSP with a minimalist feature, we can include [HoverClientCapabilities]([HoverClientCapabilities](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#hoverClientCapabilities).

- [x] Add `HoverClientCapabilitie` to LSP
- [x] Make it work with the VS Code client (there was nothing to do)
- [x] Pull analysis from the type-checking engine
  - [x] Show information from the `SemanticAnalyzer`
  - [x] Pull information from the `TypeChecker`

**Comment by Glyphack** [comment]
This is done right now, the remaining work is in the type checker and type evaluator logic.
